version: '3.8'

services:
  nodejs:
    build:
      context: ./
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    user: "1000:1000"
    command: /bin/sh ./start.sh
    networks:
      - bitpay

networks:
  bitpay:

